# #PRINT IS USED FOR DISPLAY AN OUTPUT IN OUR PROGRAMM
# print("hello world")
# #Bio-data
# name="siddhartha mekapothula"
# age="19"
# college="MRCET"
# branch="csm"
# place="suryapet"
# print("my name is",name)
# print("my age is",age)
# print("my college is",college)
# print("my branch is",branch)
# print("my place is",place)
#Bio data using input and output statements
name=input("enter your name:")
age=input("enter your age:")
college=input("enter your college:")
branch=input("enter your branch:")
place=input("enter your place:")
print("Name:",name)
print("My age is:",age)
print("my college:",college)
print("my branch is:",branch)
print("my place is:",place)
