
#operators
# p1=5
# q1=10
# #or
# print(p1>2 or q1>5)
# print(p1>2 or q1<5)
# print(p1<2 or q1<5)
# print(p1<2 or q1>5)
# #and
# print(p1>2 and q1>5)
# print(p1>2 and q1<5)
# print(p1<2 and q1<5)
# print(p1<2 and q1>5)
# #assigment operator
# a1=10
# a1+=1
# print(a1)
# a1-=1
# print(a1)
# #bitwise operator
x=5
y=10
print(x&y)
print(x|y)
print(~x)
print(x^y)
print(x<<y)
print(x>>y)
# #identity operator
# x=[1,2,3,4]
# y=x
# z=[1,2,3,4]
# print(x is y)
# print(x is z)
# print(x is not z)
# #membership operator
# text=[1,2,3,4]
# print(4 not in text)
# print(4 in text)
# print(5  not in text)
# print(5 in  text)])
